/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Phishing.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Phishing.Model
{
    /// <summary>
    /// AI advanced phishing detection request
    /// </summary>
    [DataContract(Name = "PhishingDetectionAdvancedRequest")]
    public partial class PhishingDetectionAdvancedRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionAdvancedRequest" /> class.
        /// </summary>
        /// <param name="inputString">Input text string to detect phishing against.</param>
        /// <param name="textType">Optional: Type of text being analyzed. Must be one of: \&quot;TextMessage\&quot;, \&quot;UserMessage\&quot;, \&quot;SalesLead\&quot;, \&quot;EmailMessage\&quot;, \&quot;SupportCase\&quot;, \&quot;AppMessage\&quot;, \&quot;Other\&quot;..</param>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced..</param>
        /// <param name="allowUnsolicitedSales">Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true..</param>
        /// <param name="allowPromotionalContent">Optional: True if promotional content should be allowed, false otherwise. Defaults to true..</param>
        /// <param name="allowWebUrls">Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean..</param>
        /// <param name="allowPhoneNumbers">Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean..</param>
        /// <param name="allowEmailAddresses">Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \&quot;danny at somedomaine [DOT] com\&quot;) will be flagged as not clean..</param>
        /// <param name="provideUrlAnalysis">Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true..</param>
        /// <param name="customPolicyID">Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud.</param>
        /// <param name="provideAnalysisRationale">Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true..</param>
        /// <param name="fromName">Optional: Name of the sender.</param>
        /// <param name="toName">Optional: Name of the recipient.</param>
        /// <param name="fromPhoneNumber">Optional: Phone number of the sender.</param>
        /// <param name="toPhoneNumber">Optional: Phone number of the recipient.</param>
        /// <param name="fromEmailAddress">Optional: Email address of the sender.</param>
        /// <param name="toEmailAddress">Optional: Email address of the recipient.</param>
        /// <param name="priorHistory">Optional: Prior context history (e.g. message history) leading up to the current input string. If provided, the AI will take this history into account as context when evaluating the current input..</param>
        public PhishingDetectionAdvancedRequest(string inputString = default(string), string textType = default(string), string model = default(string), bool allowUnsolicitedSales = default(bool), bool allowPromotionalContent = default(bool), bool allowWebUrls = default(bool), bool allowPhoneNumbers = default(bool), bool allowEmailAddresses = default(bool), bool provideUrlAnalysis = default(bool), string customPolicyID = default(string), bool provideAnalysisRationale = default(bool), string fromName = default(string), string toName = default(string), string fromPhoneNumber = default(string), string toPhoneNumber = default(string), string fromEmailAddress = default(string), string toEmailAddress = default(string), List<PriorHistoryItem> priorHistory = default(List<PriorHistoryItem>))
        {
            this.InputString = inputString;
            this.TextType = textType;
            this.Model = model;
            this.AllowUnsolicitedSales = allowUnsolicitedSales;
            this.AllowPromotionalContent = allowPromotionalContent;
            this.AllowWebUrls = allowWebUrls;
            this.AllowPhoneNumbers = allowPhoneNumbers;
            this.AllowEmailAddresses = allowEmailAddresses;
            this.ProvideUrlAnalysis = provideUrlAnalysis;
            this.CustomPolicyID = customPolicyID;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
            this.FromName = fromName;
            this.ToName = toName;
            this.FromPhoneNumber = fromPhoneNumber;
            this.ToPhoneNumber = toPhoneNumber;
            this.FromEmailAddress = fromEmailAddress;
            this.ToEmailAddress = toEmailAddress;
            this.PriorHistory = priorHistory;
        }

        /// <summary>
        /// Input text string to detect phishing against
        /// </summary>
        /// <value>Input text string to detect phishing against</value>
        /*
        <example>Hello, world!</example>
        */
        [DataMember(Name = "InputString", EmitDefaultValue = false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Type of text being analyzed. Must be one of: \&quot;TextMessage\&quot;, \&quot;UserMessage\&quot;, \&quot;SalesLead\&quot;, \&quot;EmailMessage\&quot;, \&quot;SupportCase\&quot;, \&quot;AppMessage\&quot;, \&quot;Other\&quot;.
        /// </summary>
        /// <value>Optional: Type of text being analyzed. Must be one of: \&quot;TextMessage\&quot;, \&quot;UserMessage\&quot;, \&quot;SalesLead\&quot;, \&quot;EmailMessage\&quot;, \&quot;SupportCase\&quot;, \&quot;AppMessage\&quot;, \&quot;Other\&quot;.</value>
        /*
        <example>TextMessage</example>
        */
        [DataMember(Name = "TextType", EmitDefaultValue = false)]
        public string TextType { get; set; }

        /// <summary>
        /// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
        /// </summary>
        /// <value>Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.</value>
        /*
        <example>Advanced</example>
        */
        [DataMember(Name = "Model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true.
        /// </summary>
        /// <value>Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowUnsolicitedSales", EmitDefaultValue = true)]
        public bool AllowUnsolicitedSales { get; set; }

        /// <summary>
        /// Optional: True if promotional content should be allowed, false otherwise. Defaults to true.
        /// </summary>
        /// <value>Optional: True if promotional content should be allowed, false otherwise. Defaults to true.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowPromotionalContent", EmitDefaultValue = true)]
        public bool AllowPromotionalContent { get; set; }

        /// <summary>
        /// Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean.
        /// </summary>
        /// <value>Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowWebUrls", EmitDefaultValue = true)]
        public bool AllowWebUrls { get; set; }

        /// <summary>
        /// Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean.
        /// </summary>
        /// <value>Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowPhoneNumbers", EmitDefaultValue = true)]
        public bool AllowPhoneNumbers { get; set; }

        /// <summary>
        /// Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \&quot;danny at somedomaine [DOT] com\&quot;) will be flagged as not clean.
        /// </summary>
        /// <value>Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \&quot;danny at somedomaine [DOT] com\&quot;) will be flagged as not clean.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "AllowEmailAddresses", EmitDefaultValue = true)]
        public bool AllowEmailAddresses { get; set; }

        /// <summary>
        /// Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true.
        /// </summary>
        /// <value>Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "ProvideUrlAnalysis", EmitDefaultValue = true)]
        public bool ProvideUrlAnalysis { get; set; }

        /// <summary>
        /// Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
        /// </summary>
        /// <value>Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud</value>
        [DataMember(Name = "CustomPolicyID", EmitDefaultValue = false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.
        /// </summary>
        /// <value>Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "ProvideAnalysisRationale", EmitDefaultValue = true)]
        public bool ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Optional: Name of the sender
        /// </summary>
        /// <value>Optional: Name of the sender</value>
        /*
        <example>John Smith</example>
        */
        [DataMember(Name = "FromName", EmitDefaultValue = false)]
        public string FromName { get; set; }

        /// <summary>
        /// Optional: Name of the recipient
        /// </summary>
        /// <value>Optional: Name of the recipient</value>
        /*
        <example>Jane Doe</example>
        */
        [DataMember(Name = "ToName", EmitDefaultValue = false)]
        public string ToName { get; set; }

        /// <summary>
        /// Optional: Phone number of the sender
        /// </summary>
        /// <value>Optional: Phone number of the sender</value>
        /*
        <example>+1-555-123-4567</example>
        */
        [DataMember(Name = "FromPhoneNumber", EmitDefaultValue = false)]
        public string FromPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Phone number of the recipient
        /// </summary>
        /// <value>Optional: Phone number of the recipient</value>
        /*
        <example>+1-555-987-6543</example>
        */
        [DataMember(Name = "ToPhoneNumber", EmitDefaultValue = false)]
        public string ToPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Email address of the sender
        /// </summary>
        /// <value>Optional: Email address of the sender</value>
        /*
        <example>john.smith@cloudmersive.com</example>
        */
        [DataMember(Name = "FromEmailAddress", EmitDefaultValue = false)]
        public string FromEmailAddress { get; set; }

        /// <summary>
        /// Optional: Email address of the recipient
        /// </summary>
        /// <value>Optional: Email address of the recipient</value>
        /*
        <example>jane.doe@cloudmersive.com</example>
        */
        [DataMember(Name = "ToEmailAddress", EmitDefaultValue = false)]
        public string ToEmailAddress { get; set; }

        /// <summary>
        /// Optional: Prior context history (e.g. message history) leading up to the current input string. If provided, the AI will take this history into account as context when evaluating the current input.
        /// </summary>
        /// <value>Optional: Prior context history (e.g. message history) leading up to the current input string. If provided, the AI will take this history into account as context when evaluating the current input.</value>
        [DataMember(Name = "PriorHistory", EmitDefaultValue = false)]
        public List<PriorHistoryItem> PriorHistory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionAdvancedRequest {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  TextType: ").Append(TextType).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  AllowUnsolicitedSales: ").Append(AllowUnsolicitedSales).Append("\n");
            sb.Append("  AllowPromotionalContent: ").Append(AllowPromotionalContent).Append("\n");
            sb.Append("  AllowWebUrls: ").Append(AllowWebUrls).Append("\n");
            sb.Append("  AllowPhoneNumbers: ").Append(AllowPhoneNumbers).Append("\n");
            sb.Append("  AllowEmailAddresses: ").Append(AllowEmailAddresses).Append("\n");
            sb.Append("  ProvideUrlAnalysis: ").Append(ProvideUrlAnalysis).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  FromPhoneNumber: ").Append(FromPhoneNumber).Append("\n");
            sb.Append("  ToPhoneNumber: ").Append(ToPhoneNumber).Append("\n");
            sb.Append("  FromEmailAddress: ").Append(FromEmailAddress).Append("\n");
            sb.Append("  ToEmailAddress: ").Append(ToEmailAddress).Append("\n");
            sb.Append("  PriorHistory: ").Append(PriorHistory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
