/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Phishing.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Phishing.Model
{
    /// <summary>
    /// Result of detecting phishing from a URL using AI
    /// </summary>
    [DataContract(Name = "PhishingDetectionUrlAdvancedResponse")]
    public partial class PhishingDetectionUrlAdvancedResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionUrlAdvancedResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the result is not phishing (clean), and false otherwise.</param>
        /// <param name="phishingRiskLevel">Overall phishing risk level between 0.0 and 1.0.</param>
        /// <param name="isSsrfThreat">True if the URL is an SSRF threat.</param>
        /// <param name="containsPhishing">True if the URL contains phishing threat risks, false otherwise.</param>
        /// <param name="containsUnsolicitedSales">True if the URL contains unsolicited sales, false otherwise.</param>
        /// <param name="containsPromotionalContent">True if the URL contains promotional content, false otherwise.</param>
        /// <param name="containsPhishingAttempt">True if the URL contains a phishing attempt, false otherwise.</param>
        /// <param name="analysisRationale">Rationale for why the conclusion was formed.</param>
        public PhishingDetectionUrlAdvancedResponse(bool cleanResult = default(bool), double phishingRiskLevel = default(double), bool isSsrfThreat = default(bool), bool containsPhishing = default(bool), bool containsUnsolicitedSales = default(bool), bool containsPromotionalContent = default(bool), bool containsPhishingAttempt = default(bool), string analysisRationale = default(string))
        {
            this.CleanResult = cleanResult;
            this.PhishingRiskLevel = phishingRiskLevel;
            this.IsSsrfThreat = isSsrfThreat;
            this.ContainsPhishing = containsPhishing;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
            this.AnalysisRationale = analysisRationale;
        }

        /// <summary>
        /// True if the result is not phishing (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not phishing (clean), and false otherwise</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// Overall phishing risk level between 0.0 and 1.0
        /// </summary>
        /// <value>Overall phishing risk level between 0.0 and 1.0</value>
        [DataMember(Name = "PhishingRiskLevel", EmitDefaultValue = false)]
        public double PhishingRiskLevel { get; set; }

        /// <summary>
        /// True if the URL is an SSRF threat
        /// </summary>
        /// <value>True if the URL is an SSRF threat</value>
        [DataMember(Name = "IsSsrfThreat", EmitDefaultValue = true)]
        public bool IsSsrfThreat { get; set; }

        /// <summary>
        /// True if the URL contains phishing threat risks, false otherwise
        /// </summary>
        /// <value>True if the URL contains phishing threat risks, false otherwise</value>
        [DataMember(Name = "ContainsPhishing", EmitDefaultValue = true)]
        public bool ContainsPhishing { get; set; }

        /// <summary>
        /// True if the URL contains unsolicited sales, false otherwise
        /// </summary>
        /// <value>True if the URL contains unsolicited sales, false otherwise</value>
        [DataMember(Name = "ContainsUnsolicitedSales", EmitDefaultValue = true)]
        public bool ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// True if the URL contains promotional content, false otherwise
        /// </summary>
        /// <value>True if the URL contains promotional content, false otherwise</value>
        [DataMember(Name = "ContainsPromotionalContent", EmitDefaultValue = true)]
        public bool ContainsPromotionalContent { get; set; }

        /// <summary>
        /// True if the URL contains a phishing attempt, false otherwise
        /// </summary>
        /// <value>True if the URL contains a phishing attempt, false otherwise</value>
        [DataMember(Name = "ContainsPhishingAttempt", EmitDefaultValue = true)]
        public bool ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Rationale for why the conclusion was formed
        /// </summary>
        /// <value>Rationale for why the conclusion was formed</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionUrlAdvancedResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  PhishingRiskLevel: ").Append(PhishingRiskLevel).Append("\n");
            sb.Append("  IsSsrfThreat: ").Append(IsSsrfThreat).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
