/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Phishing.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Phishing.Model
{
    /// <summary>
    /// AI advanced phishing detection request
    /// </summary>
    [DataContract(Name = "PhishingDetectionAdvancedRequest")]
    public partial class PhishingDetectionAdvancedRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionAdvancedRequest" /> class.
        /// </summary>
        /// <param name="inputString">Input text string to detect phishing against.</param>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced..</param>
        /// <param name="customPolicyID">Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud.</param>
        /// <param name="provideAnalysisRationale">Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true..</param>
        /// <param name="textType">Optional: Type of text being analyzed. Must be one of: \&quot;Text Message\&quot;, \&quot;User Message\&quot;, \&quot;Sales Lead\&quot;, \&quot;Email Message\&quot;, \&quot;Support Case\&quot;, \&quot;Other\&quot;..</param>
        /// <param name="fromName">Optional: Name of the sender.</param>
        /// <param name="toName">Optional: Name of the recipient.</param>
        /// <param name="fromPhoneNumber">Optional: Phone number of the sender.</param>
        /// <param name="toPhoneNumber">Optional: Phone number of the recipient.</param>
        /// <param name="fromEmailAddress">Optional: Email address of the sender.</param>
        /// <param name="toEmailAddress">Optional: Email address of the recipient.</param>
        public PhishingDetectionAdvancedRequest(string inputString = default(string), string model = default(string), string customPolicyID = default(string), bool provideAnalysisRationale = default(bool), string textType = default(string), string fromName = default(string), string toName = default(string), string fromPhoneNumber = default(string), string toPhoneNumber = default(string), string fromEmailAddress = default(string), string toEmailAddress = default(string))
        {
            this.InputString = inputString;
            this.Model = model;
            this.CustomPolicyID = customPolicyID;
            this.ProvideAnalysisRationale = provideAnalysisRationale;
            this.TextType = textType;
            this.FromName = fromName;
            this.ToName = toName;
            this.FromPhoneNumber = fromPhoneNumber;
            this.ToPhoneNumber = toPhoneNumber;
            this.FromEmailAddress = fromEmailAddress;
            this.ToEmailAddress = toEmailAddress;
        }

        /// <summary>
        /// Input text string to detect phishing against
        /// </summary>
        /// <value>Input text string to detect phishing against</value>
        [DataMember(Name = "InputString", EmitDefaultValue = false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
        /// </summary>
        /// <value>Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.</value>
        [DataMember(Name = "Model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
        /// </summary>
        /// <value>Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud</value>
        [DataMember(Name = "CustomPolicyID", EmitDefaultValue = false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.
        /// </summary>
        /// <value>Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.</value>
        [DataMember(Name = "ProvideAnalysisRationale", EmitDefaultValue = true)]
        public bool ProvideAnalysisRationale { get; set; }

        /// <summary>
        /// Optional: Type of text being analyzed. Must be one of: \&quot;Text Message\&quot;, \&quot;User Message\&quot;, \&quot;Sales Lead\&quot;, \&quot;Email Message\&quot;, \&quot;Support Case\&quot;, \&quot;Other\&quot;.
        /// </summary>
        /// <value>Optional: Type of text being analyzed. Must be one of: \&quot;Text Message\&quot;, \&quot;User Message\&quot;, \&quot;Sales Lead\&quot;, \&quot;Email Message\&quot;, \&quot;Support Case\&quot;, \&quot;Other\&quot;.</value>
        [DataMember(Name = "TextType", EmitDefaultValue = false)]
        public string TextType { get; set; }

        /// <summary>
        /// Optional: Name of the sender
        /// </summary>
        /// <value>Optional: Name of the sender</value>
        [DataMember(Name = "FromName", EmitDefaultValue = false)]
        public string FromName { get; set; }

        /// <summary>
        /// Optional: Name of the recipient
        /// </summary>
        /// <value>Optional: Name of the recipient</value>
        [DataMember(Name = "ToName", EmitDefaultValue = false)]
        public string ToName { get; set; }

        /// <summary>
        /// Optional: Phone number of the sender
        /// </summary>
        /// <value>Optional: Phone number of the sender</value>
        [DataMember(Name = "FromPhoneNumber", EmitDefaultValue = false)]
        public string FromPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Phone number of the recipient
        /// </summary>
        /// <value>Optional: Phone number of the recipient</value>
        [DataMember(Name = "ToPhoneNumber", EmitDefaultValue = false)]
        public string ToPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Email address of the sender
        /// </summary>
        /// <value>Optional: Email address of the sender</value>
        [DataMember(Name = "FromEmailAddress", EmitDefaultValue = false)]
        public string FromEmailAddress { get; set; }

        /// <summary>
        /// Optional: Email address of the recipient
        /// </summary>
        /// <value>Optional: Email address of the recipient</value>
        [DataMember(Name = "ToEmailAddress", EmitDefaultValue = false)]
        public string ToEmailAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionAdvancedRequest {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("  ProvideAnalysisRationale: ").Append(ProvideAnalysisRationale).Append("\n");
            sb.Append("  TextType: ").Append(TextType).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  FromPhoneNumber: ").Append(FromPhoneNumber).Append("\n");
            sb.Append("  ToPhoneNumber: ").Append(ToPhoneNumber).Append("\n");
            sb.Append("  FromEmailAddress: ").Append(FromEmailAddress).Append("\n");
            sb.Append("  ToEmailAddress: ").Append(ToEmailAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
