/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Phishing.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Phishing.Model
{
    /// <summary>
    /// Result of detecting phishing using AI
    /// </summary>
    [DataContract(Name = "PhishingDetectionAdvancedResponse")]
    public partial class PhishingDetectionAdvancedResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionAdvancedResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the result is not phishing (clean), and false otherwise.</param>
        /// <param name="containsPhishing">True if the input text contains a phishing attempt, false otherwise.</param>
        /// <param name="containsUnsolicitedSales">True if the input text contains unsolicited sales, false otherwise.</param>
        /// <param name="containsPromotionalContent">True if the input text contains promotional content, false otherwise.</param>
        /// <param name="containsWebUrls">True if the input text contains web URLs, including homoglyph URLs and spaced-out URL workarounds.</param>
        /// <param name="containsPhoneNumbers">True if the input text contains phone numbers, including homoglyph digits and spaced-out or spelled-out workarounds.</param>
        /// <param name="containsEmailAddresses">True if the input text contains email addresses, including homoglyph characters and obfuscated workarounds.</param>
        /// <param name="confidenceLevel">Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence.</param>
        /// <param name="analysisRationale">Rationale for why the conclusion was formed.</param>
        /// <param name="unsafeUrls">URLs detected in the input text that were analyzed and found to be unsafe. Only populated when ProvideUrlAnalysis is true and URLs are detected..</param>
        public PhishingDetectionAdvancedResponse(bool cleanResult = default(bool), bool containsPhishing = default(bool), bool containsUnsolicitedSales = default(bool), bool containsPromotionalContent = default(bool), bool containsWebUrls = default(bool), bool containsPhoneNumbers = default(bool), bool containsEmailAddresses = default(bool), double confidenceLevel = default(double), string analysisRationale = default(string), List<UnsafeUrlResult> unsafeUrls = default(List<UnsafeUrlResult>))
        {
            this.CleanResult = cleanResult;
            this.ContainsPhishing = containsPhishing;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsWebUrls = containsWebUrls;
            this.ContainsPhoneNumbers = containsPhoneNumbers;
            this.ContainsEmailAddresses = containsEmailAddresses;
            this.ConfidenceLevel = confidenceLevel;
            this.AnalysisRationale = analysisRationale;
            this.UnsafeUrls = unsafeUrls;
        }

        /// <summary>
        /// True if the result is not phishing (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not phishing (clean), and false otherwise</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// True if the input text contains a phishing attempt, false otherwise
        /// </summary>
        /// <value>True if the input text contains a phishing attempt, false otherwise</value>
        [DataMember(Name = "ContainsPhishing", EmitDefaultValue = true)]
        public bool ContainsPhishing { get; set; }

        /// <summary>
        /// True if the input text contains unsolicited sales, false otherwise
        /// </summary>
        /// <value>True if the input text contains unsolicited sales, false otherwise</value>
        [DataMember(Name = "ContainsUnsolicitedSales", EmitDefaultValue = true)]
        public bool ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// True if the input text contains promotional content, false otherwise
        /// </summary>
        /// <value>True if the input text contains promotional content, false otherwise</value>
        [DataMember(Name = "ContainsPromotionalContent", EmitDefaultValue = true)]
        public bool ContainsPromotionalContent { get; set; }

        /// <summary>
        /// True if the input text contains web URLs, including homoglyph URLs and spaced-out URL workarounds
        /// </summary>
        /// <value>True if the input text contains web URLs, including homoglyph URLs and spaced-out URL workarounds</value>
        [DataMember(Name = "ContainsWebUrls", EmitDefaultValue = true)]
        public bool ContainsWebUrls { get; set; }

        /// <summary>
        /// True if the input text contains phone numbers, including homoglyph digits and spaced-out or spelled-out workarounds
        /// </summary>
        /// <value>True if the input text contains phone numbers, including homoglyph digits and spaced-out or spelled-out workarounds</value>
        [DataMember(Name = "ContainsPhoneNumbers", EmitDefaultValue = true)]
        public bool ContainsPhoneNumbers { get; set; }

        /// <summary>
        /// True if the input text contains email addresses, including homoglyph characters and obfuscated workarounds
        /// </summary>
        /// <value>True if the input text contains email addresses, including homoglyph characters and obfuscated workarounds</value>
        [DataMember(Name = "ContainsEmailAddresses", EmitDefaultValue = true)]
        public bool ContainsEmailAddresses { get; set; }

        /// <summary>
        /// Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence
        /// </summary>
        /// <value>Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence</value>
        [DataMember(Name = "ConfidenceLevel", EmitDefaultValue = false)]
        public double ConfidenceLevel { get; set; }

        /// <summary>
        /// Rationale for why the conclusion was formed
        /// </summary>
        /// <value>Rationale for why the conclusion was formed</value>
        [DataMember(Name = "AnalysisRationale", EmitDefaultValue = false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// URLs detected in the input text that were analyzed and found to be unsafe. Only populated when ProvideUrlAnalysis is true and URLs are detected.
        /// </summary>
        /// <value>URLs detected in the input text that were analyzed and found to be unsafe. Only populated when ProvideUrlAnalysis is true and URLs are detected.</value>
        [DataMember(Name = "UnsafeUrls", EmitDefaultValue = false)]
        public List<UnsafeUrlResult> UnsafeUrls { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhishingDetectionAdvancedResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsWebUrls: ").Append(ContainsWebUrls).Append("\n");
            sb.Append("  ContainsPhoneNumbers: ").Append(ContainsPhoneNumbers).Append("\n");
            sb.Append("  ContainsEmailAddresses: ").Append(ContainsEmailAddresses).Append("\n");
            sb.Append("  ConfidenceLevel: ").Append(ConfidenceLevel).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("  UnsafeUrls: ").Append(UnsafeUrls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
