/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Phishing.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Phishing.Model
{
    /// <summary>
    /// A single message in the prior conversation history
    /// </summary>
    [DataContract(Name = "PriorHistoryItem")]
    public partial class PriorHistoryItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriorHistoryItem" /> class.
        /// </summary>
        /// <param name="inputString">The text content of this historical message.</param>
        /// <param name="fromName">Optional: Name of the sender.</param>
        /// <param name="toName">Optional: Name of the recipient.</param>
        /// <param name="fromPhoneNumber">Optional: Phone number of the sender.</param>
        /// <param name="toPhoneNumber">Optional: Phone number of the recipient.</param>
        /// <param name="fromEmailAddress">Optional: Email address of the sender.</param>
        /// <param name="toEmailAddress">Optional: Email address of the recipient.</param>
        /// <param name="trustedParty">Optional: True if this message is from a trusted party (such as our own company), false otherwise.</param>
        public PriorHistoryItem(string inputString = default(string), string fromName = default(string), string toName = default(string), string fromPhoneNumber = default(string), string toPhoneNumber = default(string), string fromEmailAddress = default(string), string toEmailAddress = default(string), bool trustedParty = default(bool))
        {
            this.InputString = inputString;
            this.FromName = fromName;
            this.ToName = toName;
            this.FromPhoneNumber = fromPhoneNumber;
            this.ToPhoneNumber = toPhoneNumber;
            this.FromEmailAddress = fromEmailAddress;
            this.ToEmailAddress = toEmailAddress;
            this.TrustedParty = trustedParty;
        }

        /// <summary>
        /// The text content of this historical message
        /// </summary>
        /// <value>The text content of this historical message</value>
        /*
        <example>Hello, how can I help you today?</example>
        */
        [DataMember(Name = "InputString", EmitDefaultValue = false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Name of the sender
        /// </summary>
        /// <value>Optional: Name of the sender</value>
        /*
        <example>John Smith</example>
        */
        [DataMember(Name = "FromName", EmitDefaultValue = false)]
        public string FromName { get; set; }

        /// <summary>
        /// Optional: Name of the recipient
        /// </summary>
        /// <value>Optional: Name of the recipient</value>
        /*
        <example>Jane Doe</example>
        */
        [DataMember(Name = "ToName", EmitDefaultValue = false)]
        public string ToName { get; set; }

        /// <summary>
        /// Optional: Phone number of the sender
        /// </summary>
        /// <value>Optional: Phone number of the sender</value>
        /*
        <example>+1-555-123-4567</example>
        */
        [DataMember(Name = "FromPhoneNumber", EmitDefaultValue = false)]
        public string FromPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Phone number of the recipient
        /// </summary>
        /// <value>Optional: Phone number of the recipient</value>
        /*
        <example>+1-555-987-6543</example>
        */
        [DataMember(Name = "ToPhoneNumber", EmitDefaultValue = false)]
        public string ToPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Email address of the sender
        /// </summary>
        /// <value>Optional: Email address of the sender</value>
        /*
        <example>john.smith@cloudmersive.com</example>
        */
        [DataMember(Name = "FromEmailAddress", EmitDefaultValue = false)]
        public string FromEmailAddress { get; set; }

        /// <summary>
        /// Optional: Email address of the recipient
        /// </summary>
        /// <value>Optional: Email address of the recipient</value>
        /*
        <example>jane.doe@cloudmersive.com</example>
        */
        [DataMember(Name = "ToEmailAddress", EmitDefaultValue = false)]
        public string ToEmailAddress { get; set; }

        /// <summary>
        /// Optional: True if this message is from a trusted party (such as our own company), false otherwise
        /// </summary>
        /// <value>Optional: True if this message is from a trusted party (such as our own company), false otherwise</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "TrustedParty", EmitDefaultValue = true)]
        public bool TrustedParty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PriorHistoryItem {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  FromPhoneNumber: ").Append(FromPhoneNumber).Append("\n");
            sb.Append("  ToPhoneNumber: ").Append(ToPhoneNumber).Append("\n");
            sb.Append("  FromEmailAddress: ").Append(FromEmailAddress).Append("\n");
            sb.Append("  ToEmailAddress: ").Append(ToEmailAddress).Append("\n");
            sb.Append("  TrustedParty: ").Append(TrustedParty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
