/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Phishing.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Phishing.Model
{
    /// <summary>
    /// Result of analyzing an individual URL found in text
    /// </summary>
    [DataContract(Name = "UnsafeUrlResult")]
    public partial class UnsafeUrlResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsafeUrlResult" /> class.
        /// </summary>
        /// <param name="url">The URL that was detected and analyzed.</param>
        /// <param name="cleanResult">True if the result is not phishing (clean), and false otherwise.</param>
        /// <param name="isSsrfThreat">True if the URL is an SSRF threat.</param>
        /// <param name="containsPhishing">True if the URL contains phishing threat risks, false otherwise.</param>
        /// <param name="containsPhishingAttempt">True if the URL contains a phishing attempt, false otherwise.</param>
        public UnsafeUrlResult(string url = default(string), bool cleanResult = default(bool), bool isSsrfThreat = default(bool), bool containsPhishing = default(bool), bool containsPhishingAttempt = default(bool))
        {
            this.Url = url;
            this.CleanResult = cleanResult;
            this.IsSsrfThreat = isSsrfThreat;
            this.ContainsPhishing = containsPhishing;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
        }

        /// <summary>
        /// The URL that was detected and analyzed
        /// </summary>
        /// <value>The URL that was detected and analyzed</value>
        [DataMember(Name = "Url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// True if the result is not phishing (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not phishing (clean), and false otherwise</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// True if the URL is an SSRF threat
        /// </summary>
        /// <value>True if the URL is an SSRF threat</value>
        [DataMember(Name = "IsSsrfThreat", EmitDefaultValue = true)]
        public bool IsSsrfThreat { get; set; }

        /// <summary>
        /// True if the URL contains phishing threat risks, false otherwise
        /// </summary>
        /// <value>True if the URL contains phishing threat risks, false otherwise</value>
        [DataMember(Name = "ContainsPhishing", EmitDefaultValue = true)]
        public bool ContainsPhishing { get; set; }

        /// <summary>
        /// True if the URL contains a phishing attempt, false otherwise
        /// </summary>
        /// <value>True if the URL contains a phishing attempt, false otherwise</value>
        [DataMember(Name = "ContainsPhishingAttempt", EmitDefaultValue = true)]
        public bool ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnsafeUrlResult {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  IsSsrfThreat: ").Append(IsSsrfThreat).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
