/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NET.Phishing.Client;
using Cloudmersive.APIClient.NET.Phishing.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.Phishing.Model;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Api
{
    /// <summary>
    ///  Class for testing PhishingDetectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PhishingDetectionApiTests : IDisposable
    {
        private PhishingDetectionApi instance;

        public PhishingDetectionApiTests()
        {
            instance = new PhishingDetectionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PhishingDetectionApi
            //Assert.IsType<PhishingDetectionApi>(instance);
        }

        /// <summary>
        /// Test PhishingDetectEmailAdvancedPost
        /// </summary>
        [Fact]
        public void PhishingDetectEmailAdvancedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AdvancedEmailDetectionRequest body = null;
            //var response = instance.PhishingDetectEmailAdvancedPost(body);
            //Assert.IsType<PhishingDetectionEmailAdvancedResponse>(response);
        }

        /// <summary>
        /// Test PhishingDetectFileAdvancedPost
        /// </summary>
        [Fact]
        public void PhishingDetectFileAdvancedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.PhishingDetectFileAdvancedPost(model, inputFile);
            //Assert.IsType<PhishingDetectionAdvancedResponse>(response);
        }

        /// <summary>
        /// Test PhishingDetectFilePost
        /// </summary>
        [Fact]
        public void PhishingDetectFilePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string model = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.PhishingDetectFilePost(model, inputFile);
            //Assert.IsType<PhishingDetectionResponse>(response);
        }

        /// <summary>
        /// Test PhishingDetectTextStringAdvancedPost
        /// </summary>
        [Fact]
        public void PhishingDetectTextStringAdvancedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PhishingDetectionAdvancedRequest body = null;
            //var response = instance.PhishingDetectTextStringAdvancedPost(body);
            //Assert.IsType<PhishingDetectionAdvancedResponse>(response);
        }
    }
}
