. .\core.ps1

Remove-Item –path ./client –recurse

Invoke-WebRequest -Uri 'https://api.cloudmersive.com/phishing/v1/swagger.json' -OutFile '.\phishing-api-swagger.json'
(Get-Content .\phishing-api-swagger.json).replace('localhost', "api.cloudmersive.com") | Set-Content .\phishing-api-swagger.json
(Get-Content .\phishing-api-swagger.json).replace('"http"', '"https"') | Set-Content .\phishing-api-swagger.json

java -jar ./openapi-generator-cli-7.12.0.jar generate -i .\phishing-api-swagger.json -g csharp -o client -c packageconfig.json

## (Get-Content ./client/src/api/ConvertDocumentApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertDocumentApi.js
## (Get-Content ./client/src/api/ConvertWebApi.js).replace('var returnType = Object;', "var returnType = 'Blob';") | Set-Content ./client/src/api/ConvertWebApi.js
## & npm build ./client


$csprojpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.Phishing/Cloudmersive.APIClient.NET.Phishing.csproj
$csprojtestpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.Phishing.Test/Cloudmersive.APIClient.NET.Phishing.Test.csproj
#$nuspecpath = Resolve-Path ./client/src/Cloudmersive.APIClient.NET.VirusScan/Cloudmersive.APIClient.NET.VirusScan.nuspec
$slnpath = Resolve-Path ./client/Cloudmersive.APIClient.NET.Phishing.sln




(Get-Content $csprojpath).replace('<RepositoryUrl>https://github.com/Cloudmersive/Cloudmersive.APIClient.NET.Phishing.git</RepositoryUrl>', '<RepositoryUrl>https://github.com/Cloudmersive/Cloudmersive.APIClient.NET.Phishing.git</RepositoryUrl><PackageProjectUrl>https://cloudmersive.com/spam-detection-api</PackageProjectUrl><PackageIconUrl>https://cloudmersive.com/images/cmsdk.png</PackageIconUrl>') | Set-Content $csprojpath




./nuget.exe restore $csprojpath -SolutionDirectory ./client

./nuget.exe restore $csprojtestpath -SolutionDirectory ./client

#C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe $slnpath /t:rebuild 
$configuration = 'Release'

dotnet build $slnpath -c $configuration

#$msbuild = Get-LatestMsBuild
#& $msbuild $slnpath /t:Rebuild /p:Configuration=$configuration



#& C:\CodeSigning\sign.ps1 ./client/src/Cloudmersive.APIClient.NET.Phishing/bin/Debug/netstandard2.0/Cloudmersive.APIClient.NET.Phishing.dll
#& C:\CodeSigning\sign.ps1 ./client/src/Cloudmersive.APIClient.NET.Phishing/bin/Release/netstandard2.0/Cloudmersive.APIClient.NET.Phishing.dll

Write-Host "Packing..."

#./nuget.exe pack $csprojpath -Properties Configuration=$configuration

dotnet pack  $csprojpath -c $configuration -o ./nupkgs

(Get-Content ./client/README.md).replace(' automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project', " for the [Cloudmersive Phishing Detection API](https://cloudmersive.com/phishing-detection-api)") | Set-Content ./client/README.md

Copy-Item ./client/README.md ./README.md