/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing AdvancedUrlDetectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdvancedUrlDetectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdvancedUrlDetectionRequest
        //private AdvancedUrlDetectionRequest instance;

        public AdvancedUrlDetectionRequestTests()
        {
            // TODO uncomment below to create an instance of AdvancedUrlDetectionRequest
            //instance = new AdvancedUrlDetectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdvancedUrlDetectionRequest
        /// </summary>
        [Fact]
        public void AdvancedUrlDetectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdvancedUrlDetectionRequest
            //Assert.IsType<AdvancedUrlDetectionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
