/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing AdvancedEmailDetectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdvancedEmailDetectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdvancedEmailDetectionRequest
        //private AdvancedEmailDetectionRequest instance;

        public AdvancedEmailDetectionRequestTests()
        {
            // TODO uncomment below to create an instance of AdvancedEmailDetectionRequest
            //instance = new AdvancedEmailDetectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdvancedEmailDetectionRequest
        /// </summary>
        [Fact]
        public void AdvancedEmailDetectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdvancedEmailDetectionRequest
            //Assert.IsType<AdvancedEmailDetectionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'FromEmailAddress'
        /// </summary>
        [Fact]
        public void FromEmailAddressTest()
        {
            // TODO unit test for the property 'FromEmailAddress'
        }

        /// <summary>
        /// Test the property 'ToEmailAddress'
        /// </summary>
        [Fact]
        public void ToEmailAddressTest()
        {
            // TODO unit test for the property 'ToEmailAddress'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'HtmlBody'
        /// </summary>
        [Fact]
        public void HtmlBodyTest()
        {
            // TODO unit test for the property 'HtmlBody'
        }

        /// <summary>
        /// Test the property 'AllowLowReputationSenders'
        /// </summary>
        [Fact]
        public void AllowLowReputationSendersTest()
        {
            // TODO unit test for the property 'AllowLowReputationSenders'
        }

        /// <summary>
        /// Test the property 'AllowSanctioned'
        /// </summary>
        [Fact]
        public void AllowSanctionedTest()
        {
            // TODO unit test for the property 'AllowSanctioned'
        }

        /// <summary>
        /// Test the property 'InputEmailFile'
        /// </summary>
        [Fact]
        public void InputEmailFileTest()
        {
            // TODO unit test for the property 'InputEmailFile'
        }
    }
}
