/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionResponse
        //private PhishingDetectionResponse instance;

        public PhishingDetectionResponseTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionResponse
            //instance = new PhishingDetectionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionResponse
        /// </summary>
        [Fact]
        public void PhishingDetectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionResponse
            //Assert.IsType<PhishingDetectionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
    }
}
