/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionAdvancedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionAdvancedRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionAdvancedRequest
        //private PhishingDetectionAdvancedRequest instance;

        public PhishingDetectionAdvancedRequestTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionAdvancedRequest
            //instance = new PhishingDetectionAdvancedRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionAdvancedRequest
        /// </summary>
        [Fact]
        public void PhishingDetectionAdvancedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionAdvancedRequest
            //Assert.IsType<PhishingDetectionAdvancedRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Fact]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }

        /// <summary>
        /// Test the property 'TextType'
        /// </summary>
        [Fact]
        public void TextTypeTest()
        {
            // TODO unit test for the property 'TextType'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'AllowUnsolicitedSales'
        /// </summary>
        [Fact]
        public void AllowUnsolicitedSalesTest()
        {
            // TODO unit test for the property 'AllowUnsolicitedSales'
        }

        /// <summary>
        /// Test the property 'AllowPromotionalContent'
        /// </summary>
        [Fact]
        public void AllowPromotionalContentTest()
        {
            // TODO unit test for the property 'AllowPromotionalContent'
        }

        /// <summary>
        /// Test the property 'AllowWebUrls'
        /// </summary>
        [Fact]
        public void AllowWebUrlsTest()
        {
            // TODO unit test for the property 'AllowWebUrls'
        }

        /// <summary>
        /// Test the property 'AllowPhoneNumbers'
        /// </summary>
        [Fact]
        public void AllowPhoneNumbersTest()
        {
            // TODO unit test for the property 'AllowPhoneNumbers'
        }

        /// <summary>
        /// Test the property 'AllowEmailAddresses'
        /// </summary>
        [Fact]
        public void AllowEmailAddressesTest()
        {
            // TODO unit test for the property 'AllowEmailAddresses'
        }

        /// <summary>
        /// Test the property 'ProvideUrlAnalysis'
        /// </summary>
        [Fact]
        public void ProvideUrlAnalysisTest()
        {
            // TODO unit test for the property 'ProvideUrlAnalysis'
        }

        /// <summary>
        /// Test the property 'CustomPolicyID'
        /// </summary>
        [Fact]
        public void CustomPolicyIDTest()
        {
            // TODO unit test for the property 'CustomPolicyID'
        }

        /// <summary>
        /// Test the property 'ProvideAnalysisRationale'
        /// </summary>
        [Fact]
        public void ProvideAnalysisRationaleTest()
        {
            // TODO unit test for the property 'ProvideAnalysisRationale'
        }

        /// <summary>
        /// Test the property 'FromName'
        /// </summary>
        [Fact]
        public void FromNameTest()
        {
            // TODO unit test for the property 'FromName'
        }

        /// <summary>
        /// Test the property 'ToName'
        /// </summary>
        [Fact]
        public void ToNameTest()
        {
            // TODO unit test for the property 'ToName'
        }

        /// <summary>
        /// Test the property 'FromPhoneNumber'
        /// </summary>
        [Fact]
        public void FromPhoneNumberTest()
        {
            // TODO unit test for the property 'FromPhoneNumber'
        }

        /// <summary>
        /// Test the property 'ToPhoneNumber'
        /// </summary>
        [Fact]
        public void ToPhoneNumberTest()
        {
            // TODO unit test for the property 'ToPhoneNumber'
        }

        /// <summary>
        /// Test the property 'FromEmailAddress'
        /// </summary>
        [Fact]
        public void FromEmailAddressTest()
        {
            // TODO unit test for the property 'FromEmailAddress'
        }

        /// <summary>
        /// Test the property 'ToEmailAddress'
        /// </summary>
        [Fact]
        public void ToEmailAddressTest()
        {
            // TODO unit test for the property 'ToEmailAddress'
        }
    }
}
