/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionTextStringRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionTextStringRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionTextStringRequest
        //private PhishingDetectionTextStringRequest instance;

        public PhishingDetectionTextStringRequestTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionTextStringRequest
            //instance = new PhishingDetectionTextStringRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionTextStringRequest
        /// </summary>
        [Fact]
        public void PhishingDetectionTextStringRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionTextStringRequest
            //Assert.IsType<PhishingDetectionTextStringRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Fact]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'ProvideAnalysisRationale'
        /// </summary>
        [Fact]
        public void ProvideAnalysisRationaleTest()
        {
            // TODO unit test for the property 'ProvideAnalysisRationale'
        }
    }
}
