/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionTextStringResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionTextStringResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionTextStringResponse
        //private PhishingDetectionTextStringResponse instance;

        public PhishingDetectionTextStringResponseTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionTextStringResponse
            //instance = new PhishingDetectionTextStringResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionTextStringResponse
        /// </summary>
        [Fact]
        public void PhishingDetectionTextStringResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionTextStringResponse
            //Assert.IsType<PhishingDetectionTextStringResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ConfidenceLevel'
        /// </summary>
        [Fact]
        public void ConfidenceLevelTest()
        {
            // TODO unit test for the property 'ConfidenceLevel'
        }

        /// <summary>
        /// Test the property 'AnalysisRationale'
        /// </summary>
        [Fact]
        public void AnalysisRationaleTest()
        {
            // TODO unit test for the property 'AnalysisRationale'
        }
    }
}
