/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing PhishingDetectionAdvancedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhishingDetectionAdvancedRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhishingDetectionAdvancedRequest
        //private PhishingDetectionAdvancedRequest instance;

        public PhishingDetectionAdvancedRequestTests()
        {
            // TODO uncomment below to create an instance of PhishingDetectionAdvancedRequest
            //instance = new PhishingDetectionAdvancedRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhishingDetectionAdvancedRequest
        /// </summary>
        [Fact]
        public void PhishingDetectionAdvancedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhishingDetectionAdvancedRequest
            //Assert.IsType<PhishingDetectionAdvancedRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Fact]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
    }
}
