/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing PriorHistoryItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriorHistoryItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriorHistoryItem
        //private PriorHistoryItem instance;

        public PriorHistoryItemTests()
        {
            // TODO uncomment below to create an instance of PriorHistoryItem
            //instance = new PriorHistoryItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriorHistoryItem
        /// </summary>
        [Fact]
        public void PriorHistoryItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriorHistoryItem
            //Assert.IsType<PriorHistoryItem>(instance);
        }

        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Fact]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }

        /// <summary>
        /// Test the property 'FromName'
        /// </summary>
        [Fact]
        public void FromNameTest()
        {
            // TODO unit test for the property 'FromName'
        }

        /// <summary>
        /// Test the property 'ToName'
        /// </summary>
        [Fact]
        public void ToNameTest()
        {
            // TODO unit test for the property 'ToName'
        }

        /// <summary>
        /// Test the property 'FromPhoneNumber'
        /// </summary>
        [Fact]
        public void FromPhoneNumberTest()
        {
            // TODO unit test for the property 'FromPhoneNumber'
        }

        /// <summary>
        /// Test the property 'ToPhoneNumber'
        /// </summary>
        [Fact]
        public void ToPhoneNumberTest()
        {
            // TODO unit test for the property 'ToPhoneNumber'
        }

        /// <summary>
        /// Test the property 'FromEmailAddress'
        /// </summary>
        [Fact]
        public void FromEmailAddressTest()
        {
            // TODO unit test for the property 'FromEmailAddress'
        }

        /// <summary>
        /// Test the property 'ToEmailAddress'
        /// </summary>
        [Fact]
        public void ToEmailAddressTest()
        {
            // TODO unit test for the property 'ToEmailAddress'
        }

        /// <summary>
        /// Test the property 'TrustedParty'
        /// </summary>
        [Fact]
        public void TrustedPartyTest()
        {
            // TODO unit test for the property 'TrustedParty'
        }
    }
}
