/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Phishing.Model;
using Cloudmersive.APIClient.NET.Phishing.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Phishing.Test.Model
{
    /// <summary>
    ///  Class for testing UnsafeUrlResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnsafeUrlResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnsafeUrlResult
        //private UnsafeUrlResult instance;

        public UnsafeUrlResultTests()
        {
            // TODO uncomment below to create an instance of UnsafeUrlResult
            //instance = new UnsafeUrlResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnsafeUrlResult
        /// </summary>
        [Fact]
        public void UnsafeUrlResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnsafeUrlResult
            //Assert.IsType<UnsafeUrlResult>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'IsSsrfThreat'
        /// </summary>
        [Fact]
        public void IsSsrfThreatTest()
        {
            // TODO unit test for the property 'IsSsrfThreat'
        }

        /// <summary>
        /// Test the property 'ContainsPhishing'
        /// </summary>
        [Fact]
        public void ContainsPhishingTest()
        {
            // TODO unit test for the property 'ContainsPhishing'
        }

        /// <summary>
        /// Test the property 'ContainsPhishingAttempt'
        /// </summary>
        [Fact]
        public void ContainsPhishingAttemptTest()
        {
            // TODO unit test for the property 'ContainsPhishingAttempt'
        }
    }
}
